### ISSUE TITLE
MarkdownEditor must implement method `focus`

### ISSUE THREAD

**Issue by mpcabd** [nylas/N1-Markdown-Composer#1]
I got this error when I tried this plugin:

`Uncaught Error: MarkdownEditor must implement method`focus`when registering for {"role":"Composer:Editor"}`

Thanks

**Comment by jstejada** [comment]
thanks @mpcabd , I'll update this

**Comment by jstejada** [comment]
fixed with https://github.com/nylas/N1-Markdown-Composer/commit/38e135a34682647476a90dd400bdd1ec779d5789
