### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [nylas/N1-Markdown-Composer#12]
Ubuntu 14.04

Installed following README.md; no option to convert text to markdown.

![image](https://cloud.githubusercontent.com/assets/15050878/14578702/f6309baa-035c-11e6-9a53-fe4a780fda54.png)

![image](https://cloud.githubusercontent.com/assets/15050878/14578705/1741073a-035d-11e6-99ba-3dfb81da9046.png)

**Comment by jstejada** [comment]
hey @minersrevolt this is probably due to an installation issue #9. There is a workaround at the end of that thread, let me know if that works

**Comment by ghost** [comment]
Thanks for the quick reply Juan.

I copied the downloaded git to ~/.nylas/packages

closed Nylas

ran % apm install

It checked that the modules were installed

restarted Nylas and enabled the add on and saw the attached screenshot

I am unable to type in the window. When I disable the addon the window regains
functionality.

Not sure if it's relevant but I already had Atom installed (some people seem
to think that was a requirement).

![](https://link.nylas.com/open/f2rdq5f28oshujxfcq6raqt3e/local-5181715a-6718)

**Comment by jstejada** [comment]
thanks @minersrevolt there seems to be an additional problem, I'll look into it soon
