### ISSUE TITLE
Where is the New mail editor?

### ISSUE THREAD

**Issue by zeg-io** [nylas/N1-Markdown-Composer#13]
I installed the plugin per the instructions, restarted Nylas N1, double-checked the plugin is listed as installed (it is) but when I create a new email, there is no markdown editor

Using: Version 0.4.33-e8f137e (0.4.33-e8f137e) of N1.

Also, if you happen to know where documentation for Nylas on how to format the document is, I'd love that.  I have been stumbling around trying to figure out the basic text I need to enter to create unordered and ordered lists but they don't seem to have any documentation for it.  I'd even write the docs for you if I knew where it was on GitHub.

Another example, the template example that comes with N1 includes a cool looking callout with text and a field in it... however, there isn't a way to create those from the UI that I can see.

**Comment by johanbrook** [comment]
I get the same: followed instructions on cloning the repo, running `apm install` in the `.nylas` package directory folder, but nothing shows up after restart. Not sure if any logs exist.

**Comment by blacklevel** [comment]
+1

**Comment by danielbayley** [comment]
+1. Nothing. Nada. _Still_ can't write emails in Markdown 😞

**Comment by shay-somech** [comment]
+1

**Comment by jstejada** [comment]
hi all! thanks for reporting this! these issues should be fixed as of https://github.com/nylas/N1-Markdown-Composer/commit/6a0d325d89c86c4710bd97b4dff1084a81bc5c7e.

@zeg-io you can view the markdown guide by clicking on the help icon in the markdown editor toolbar. Also, most of the composer plugins, like templates, are not compatible with the markdown plugin right now.

Thanks for your patience!
