### ISSUE TITLE
Cannot find underscore

### ISSUE THREAD

**Issue by brasilikum** [nylas/N1-Markdown-Composer#14]
according to the attached logs, underscore cannot be found.

[-1463390623870.txt](https://github.com/nylas/N1-Markdown-Composer/files/265874/-1463390623870.txt)

**Comment by youlu-cn** [comment]
It seems that underscore, react and react-dom are required, but not added in package.json.
I tried npm install them, but not work. Anyone knows which version of these 3 packages are needed?

thx

**Comment by brasilikum** [comment]
duplicate #13
