### ISSUE TITLE
Markdown editor strips HTML from signature

### ISSUE THREAD

**Issue by d3caf** [nylas/N1-Markdown-Composer#20]
It appears that when using the markdown editor, all HTML/inline CSS styling is removed from email signatures when email is sent. The preview appears fine, however.

**Comment by jamesgrant** [comment]
I'm seeing this issue as well, but it seems to be stripping basic formatting like newline characters as well as HTML.

**Comment by d3caf** [comment]
Agreed. It's stripping newline for me as well.

**Comment by jasper-lyons** [comment]
To fix this you can simply change these lines https://github.com/nylas/N1-Markdown-Composer/blob/master/lib/utils.coffee#L4-L7

```
...
  @getTextFromHtml: (html) ->
    div = document.createElement('div')
    div.innerHTML = html
    div.textContent ? div.innerText
...
```

to 

```
...
@getTextFromHtml: (html) ->
    html
...
```

This will stop the processor from stripping the html from your signature. It will leave the signature as raw html though.

**Comment by laughedelic** [comment]
@jasper-lyons could you submit a pull-request with these changes?
