### ISSUE TITLE
Editor's field is not resizing

### ISSUE THREAD

**Issue by ghost** [nylas/N1-Markdown-Composer#22]
The field is not resizeable and when my message exceeds 9 lines I cannot see anything written below, neither scrollbar appears nor the editor gets stretched.

![screenshot_2016-10-17_13-56-37](https://cloud.githubusercontent.com/assets/10786469/19436621/858b2b30-9471-11e6-99fa-909e998b28b1.png)

**Comment by laughedelic** [comment]
There's already an open issue for this problem: #4

**Comment by ghost** [comment]
Okay, then I'm closing this one. However, this is a critical issue because one cannot write more that 9 lines and this should be mentioned in #4.
