### ISSUE TITLE
Sending Raw Markdown

### ISSUE THREAD

**Issue by mjchamplin** [nylas/N1-Markdown-Composer#29]
Twice now I've composed an email, formatted it with markdown, and checked it with the `preview` button, and it's looked great. When I send it, it sends unparsed, concatenated markdown. No line breaks, plus all the markdown syntax visible. 

Anyone else having this issue? It made for an awkward email to my boss, and definitely makes for an unusable plugin.

**Comment by laughedelic** [comment]
Yes. I was also having this issue occasionally. Then I stopped using this plugin. Then I stopped using Nylas. Both the plugin and Nylas Mail are not maintained anymore..

But for Nylas Mail there is a hope: https://github.com/nylas-mail-lives/nylas-mail

**Comment by mjchamplin** [comment]
I realize now I posted this on the wrong project. Thanks for the info, @laughedelic.
