### ISSUE TITLE
Scrambled composer

### ISSUE THREAD

**Issue by furious-luke** [nylas/N1-Markdown-Composer#6]
Hi there, I'm having a problem using the markdown composer. After installation all my composer windows have scrambled contents, as in the attached picture.

![image](https://cloud.githubusercontent.com/assets/561722/13063337/0db4e466-d49b-11e5-9010-5f313c13f1cd.png)

The scrambled characters can't be deleted, and trying to type new characters doesn't work.

I'm running on Ubuntu 15.04 and have only the GitHub plugin installed in addition to the markdown plugin.

Cheers!

**Comment by johnnyfreeman** [comment]
+1

Seems like it's not loading css

**Comment by rho94** [comment]
+1

**Comment by marclafountain** [comment]
I alternate between an APM error at installation or this scrambled screen. Can't figure out what I am doing wrong.

**Comment by diederikh** [comment]
+1

**Comment by jstejada** [comment]
hi all, merging into #9 . There is a temporary workaround for the installation issue at the end of that thread

**Comment by jstejada** [comment]
the issues should be fixed now. thanks!
