### ISSUE TITLE
line break by default?

### ISSUE THREAD

**Issue by johoja12** [nylas/N1-Markdown-Composer#7]
anyway to have a single carriage return be a line break by default - this default behaviour makes copy pasting text into an email impossible.

**Comment by danielbayley** [comment]
+1. Back when Markdown Composer actually worked I remember this issue also causing the undesirable side effect of compressing the entire thread into one huge block of text.

**Comment by jstejada** [comment]
hi @saqebakhter, @danielbayley . we've updated pushed a few updates. Going to close this for now, but feel free to reopen if you're still having issues. thanks!
