### ISSUE TITLE
Doesn't send formatted mail?

### ISSUE THREAD

**Issue by bigethan** [nylas/N1-Markdown-Composer#8]
Using this plugin, my emails aren't sent with formatting.  I see this in Nylas:

<img width="912" alt="screen shot 2016-03-15 at 2 45 37 pm" src="https://cloud.githubusercontent.com/assets/627/13779708/ae03ae0c-eabc-11e5-968b-d4d44257d73e.png">

But then in gmail inbox I see:

<img width="391" alt="screen shot 2016-03-15 at 2 43 10 pm" src="https://cloud.githubusercontent.com/assets/627/13779710/b04b3b8a-eabc-11e5-80c3-30c833b06e52.png">

Anything I'm doing wrong?

**Comment by praveen12bnitt** [comment]
I also facing the same error.. Is there something that i have to do to fix this?

**Comment by moshe** [comment]
Same issue here, `OS X 10.11.3`
 `N1 Version 0.4.19-d41e72c (0.4.19-d41e72c)`

**Comment by jstejada** [comment]
hi all, this should be fixed with https://github.com/nylas/N1-Markdown-Composer/commit/74b7aa63881d7689bea8ab90a55851153437cf72
